doc:
  stage: build
  tags:
    - doc
  image: noah95/latex
  before_script:
    - apt-get update
    - apt-get install -y biber
  script:
    - pdflatex -v
    - cd doc/report/ && make
  artifacts:
    paths:
    - doc/report/p6_diip_huetter_stocker.pdf

fpga:
  stage: build
  tags:
    - vivado
  image: docker-vivado:2017.3
  before_script:
    # The following is because of a bug in vivado HLS (http://svn.clifford.at/handicraft/2017/vivadobugs/vivadobug04.txt)
    - sudo apt-get --yes --force-yes remove libgmp-dev
  script: 
    # Just for debugging
    - source /opt/Xilinx/Vivado/2017.3/settings64.sh
    - pwd
    - echo $PATH
    - id
    # Build HLS cores
    - pushd fpga/hls/
    - time make NAME=diip_faster impl
    - make NAME=wallis_8b export
    - make NAME=controller export
    - popd
    # Build HLX projects
    - pushd fpga/hlx/
    - time make NAME=diip impl
    - time make NAME=diip_faster impl
    - popd
  artifacts:
    paths:
    - "fpga/hlx/build/projects/*/*/*.dcp"
    - "fpga/hlx/build/*.bit"
    - "fpga/hlx/build/*.ltx"

# sw:
#   stage: build
#   image: ubuntu:16.04
#   before_script:
#     - apt-get update
#     - apt-get install -y gcc g++ build-essential
#     - apt-get install -y libopencv-dev
#   script:
#     - pushd sw/diip_cc/ && make && popd
#   artifacts:
#     paths:
#       - "sw/diip_cc/bin/*"