# cores:
#   stage: test
#   tags:
#     - vivado
#   image: noah-vivado:latest
#   before_script:
#     - sudo apt-get install libgnat-4.9
#     - wget https://github.com/ghdl/ghdl/releases/download/v0.33/ghdl_0.33-1jessie1_amd64.deb
#     - sudo dpkg -i ghdl_0.33-1jessie1_amd64.deb
#     - rm ghdl_0.33-1jessie1_amd64.deb
#   script:
#     - cd fpga/hlx/
#     - make TOP=uft_top_tb sim


doc:
  stage: build
  tags:
    - doc
  image: noah95/latex
  script:
    - pdflatex -v
    - cd doc/report/ && make
  artifacts:
    paths:
    - doc/report/p5_diip_huetter_stocker.pdf

fpga:
  stage: build
  tags:
    - vivado
  image: docker-vivado:2017.3
  before_script:
    # - sudo apt-get update
    # - sudo apt-get --yes --force-yes install libjpeg62 libtiff5 libgtk-3-dev libgtk2.0-0
    # Create link to libtiff5
    # - sudo ln -sf /usr/lib/x86_64-linux-gnu/libtiff.so.5 /usr/lib/x86_64-linux-gnu/libtiff.so.3

    # The following is because of a bug in vivado HLS (http://svn.clifford.at/handicraft/2017/vivadobugs/vivadobug04.txt)
    - sudo apt-get remove libgmp-dev
  script: 
    - source /opt/Xilinx/Vivado/2017.3/settings64.sh
    - pwd
    - echo $PATH
    - id
    - cd fpga/hls/controller && make
    - cd ../stream_dummy && make
    - cd ../../hlx/
    # - make NAME=sobel impl
    - time make NAME=control impl
  artifacts:
    paths:
    - fpga/hlx/build/
